In [1]:
import pandas as pd

In [2]:
df_2019 = pd.read_csv('/Users/brunogarcialopez/Documents/Data Science/Proyectos portfolio/Campeonato Europeo de Halterofilia de 2019 datos original.csv')
df_2020 = pd.read_csv('/Users/brunogarcialopez/Documents/Data Science/Proyectos portfolio/Campeonato Europeo de Halterofilia de 2020 datos original.csv')

In [3]:
df_2019.columns, df_2020.columns

(Index(['Eventos', 'Oro', 'Plata', 'Bronce', 'Año', 'Genero'], dtype='str'),
 Index(['Eventos', 'Oro', 'Plata', 'Bronce', 'Año', 'Genero'], dtype='str'))

In [4]:
display(df_2019.head())
display(df_2020.head())

,Eventos,Oro,Plata,Bronce,Año,Genero
0,55 kg (06.04),Mirco Scarantino Italia 116 + 145 = 261[n 1]​,Anguel Rusev Bulgaria 110 + 146 = 256[n 1]​,Muammer Şahin Turquía 112 + 135 = 247[n 1]​,2019,Masculino
1,61 kg (07.04),Henadz Laptseu Bielorrusia 133 + 153 = 286,Bünyamin Sezer Turquía 132 + 151 = 283,Ferdi Hardal Turquía 127 + 155 = 282,2019,Masculino
2,67 kg (08.04),Bernardin Matam Francia 137 + 175 = 312,Simon Brandhuber Alemania 146 + 165 = 311,Goga Chjeidze Georgia 139 + 169 = 308,2019,Masculino
3,73 kg (09.04),Bozhidar Andreev Bulgaria 153 + 192 = 345,Briken Calja Albania 156 + 183 = 339,Vadzim Lijarad Bielorrusia 153 + 182 = 335,2019,Masculino
4,81 kg (10.04),Antonino Pizzolato Italia 155 + 201 = 356,Piotr Asayonak Bielorrusia 159 + 196 = 355,Ritvars Suharevs Letonia 162 + 192 = 354,2019,Masculino

,Eventos,Oro,Plata,Bronce,Año,Genero
0,55 kg (04.04),Anguel Rusev Bulgaria 111 + 147 = 258[n 1]​,Valentin Iancu Rumania 108 + 140 = 248[n 1]​,Dmytro Voronovsky Ucrania 110 + 137 = 247[n 1]​,2020,Masculino
1,61 kg (04.04),Stilian Grozdev Bulgaria 136 + 160 = 296,Shota Mishvelidze Georgia 135 + 155 = 290,Ferdi Hardal Turquía 130 + 157 = 287,2020,Masculino
2,67 kg (05.04),Muhammed Özbek Turquía 145 + 178 = 323,Mirko Zanni Italia 148 + 170 = 318,Valentin Guenchev Bulgaria 138 + 177 = 315,2020,Masculino
3,73 kg (06.04),Daniyar İsmayilov Turquía 160 + 181 = 341,Marin Robu Moldavia 156 + 183 = 339,Briken Calja Albania 152 + 184 = 336,2020,Masculino
4,81 kg (07.04),Antonino Pizzolato Italia 164 + 206 = 370,Karlos Nasar Bulgaria 163 + 206 = 369,Ritvars Suharevs Letonia 157 + 190 = 347,2020,Masculino

In [5]:
# Create the translation dictionary
column_translation = {
    'Eventos': 'Events',
    'Oro': 'Gold',
    'Plata': 'Silver',
    'Bronce': 'Bronze',
    'Año': 'Year',
    'Genero': 'Gender'
}

df_2019 = df_2019.rename(columns=column_translation)
df_2020 = df_2020.rename(columns=column_translation)

In [6]:
df_2019['Gender'].unique()

<ArrowStringArray>
['Masculino', 'Femenino']
Length: 2, dtype: str

In [7]:
df_2020['Gender'].unique()

<ArrowStringArray>
['Masculino', 'Femenino']
Length: 2, dtype: str

In [8]:
traduccion = {
    'Masculino' : 'Male',
    'Femenino' : 'Female'
}

df_2019['Gender'] = df_2019['Gender'].map(traduccion)
df_2020['Gender'] = df_2020['Gender'].map(traduccion)

In [9]:
df_2019['Gender'].unique(), df_2020['Gender'].unique()

(<ArrowStringArray>
 ['Male', 'Female']
 Length: 2, dtype: str,
 <ArrowStringArray>
 ['Male', 'Female']
 Length: 2, dtype: str)

In [10]:
traduccion_paises = {
    'Italia': 'Italy',
    'Bulgaria': 'Bulgaria',
    'Turquía': 'Turkey',
    'Bielorrusia': 'Belarus',
    'Rumania': 'Romania',
    'Georgia': 'Georgia',
    'Armenia': 'Armenia',
    'Rusia': 'Russia',
    'Francia': 'France',
    'Ucrania': 'Ukraine',
    'Polonia': 'Poland',
    'Letonia': 'Latvia',
    'España': 'Spain',
    'Moldavia': 'Moldova',
    'Alemania': 'Germany',
    'Bélgica': 'Belgium',
    'Reino Unido': 'United Kingdom',
    'Azerbaiyán': 'Azerbaijan',
    'Eslovaquia': 'Slovakia',
    'Grecia': 'Greece',
    'Finlandia': 'Finland',
    'Austria': 'Austria',
    'República Checa': 'Czech Republic',
    'Israel': 'Israel',
    'Albania': 'Albania',
    'Suecia' : 'Sweden'
}

In [11]:
def traducir_paises_en_celda(texto, diccionario):
    if pd.isna(texto):
        return texto
    
    # Convertimos a string por seguridad
    texto_str = str(texto)
    
    # Buscamos cada país en español dentro del texto y lo reemplazamos por su traducción
    for pais_es, pais_en in diccionario.items():
        if pais_es in texto_str:
            # Reemplazamos el país en español por el de inglés
            texto_str = texto_str.replace(pais_es, pais_en)
            
    # Opcional: Limpiamos los molestos códigos HTML como '&nbsp;' si quedan residuos
    texto_str = texto_str.replace('&nbsp;', ' ').replace('\xa0', ' ')
    
    return texto_str

# Aplicamos la función a las columnas de medallas en ambos DataFrames
columnas_medallas = ['Gold', 'Silver', 'Bronze']

for col in columnas_medallas:
    df_2019[col] = df_2019[col].apply(lambda x: traducir_paises_en_celda(x, traduccion_paises))
    df_2020[col] = df_2020[col].apply(lambda x: traducir_paises_en_celda(x, traduccion_paises))

In [12]:
df_2019.sample(10)

,Events,Gold,Silver,Bronze,Year,Gender
14,64 kg (09.04),Loredana Toma Romania 111 + 128 = 239,Irina Lepșa Romania 102 + 127 = 229,Zoe Smith United Kingdom 96 + 128 = 224,2019,Female
8,109 kg (13.04),Simon Martirosian Armenia 192 + 235 = 427,Andrei Aramnau Belarus 190 + 221 = 411,Rodion Bochkov Russia 192 + 218 = 410,2019,Male
17,81 kg[n 2]​ (12.04),Nina Schroth Germany 102 + 120 = 222,Anna Van Bellinghen Belgium 103 + 118 = 221,Liana Guiurdzhian Armenia 97 + 120 = 217,2019,Female
2,67 kg (08.04),Bernardin Matam France 137 + 175 = 312,Simon Brandhuber Germany 146 + 165 = 311,Goga Chjeidze Georgia 139 + 169 = 308,2019,Male
12,55 kg (07.04),Joanna Łochowska Poland 87 + 112 = 199,Svetlana Yershova Russia 90 + 108 = 198,Kristina Novitskaya Russia 85 + 105 = 190,2019,Female
3,73 kg (09.04),Bozhidar Andreev Bulgaria 153 + 192 = 345,Briken Calja Albania 156 + 183 = 339,Vadzim Lijarad Belarus 153 + 182 = 335,2019,Male
18,87 kg (12.04),Xeniya Pasjina Russia 110 + 132 = 242,Diana Mstiyeva Russia 110 + 130 = 240,Sarah Fischer Austria 102 + 129 = 231,2019,Female
10,45 kg (06.04),Şaziye Erdoğan Turkey 75 + 88 = 163[n 1]​,Ivana Petrova Bulgaria 69 + 89 = 158[n 1]​,Yuliya Asayonak Belarus 69 + 81 = 150[n 1]​,2019,Female
16,76 kg (11.04),Daria Naumava Belarus 106 + 136 = 242,Lidia Valentín[2]​ Spain 108 + 133 = 241,Patricia Strenius Sweden 101 + 132 = 233,2019,Female
15,71 kg (10.04),Anastasiya Romanova Russia 112 + 128 = 240,Emily Godley United Kingdom 93 + 123 = 216,Mădălina Molie Romania 101 + 114 = 215,2019,Female

In [13]:
df_2020.sample(10)

,Events,Gold,Silver,Bronze,Year,Gender
1,61 kg (04.04),Stilian Grozdev Bulgaria 136 + 160 = 296,Shota Mishvelidze Georgia 135 + 155 = 290,Ferdi Hardal Turkey 130 + 157 = 287,2020,Male
0,55 kg (04.04),Anguel Rusev Bulgaria 111 + 147 = 258[n 1]​,Valentin Iancu Romania 108 + 140 = 248[n 1]​,Dmytro Voronovsky Ukraine 110 + 137 = 247[n 1]​,2020,Male
6,96 kg (09.04),Anton Pliesnoi Georgia 180 + 213 = 393,Piotr Asayonak Belarus 172 + 202 = 374,Hakob Mkrtchian Armenia 160 + 212 = 372,2020,Male
4,81 kg (07.04),Antonino Pizzolato Italy 164 + 206 = 370,Karlos Nasar Bulgaria 163 + 206 = 369,Ritvars Suharevs Latvia 157 + 190 = 347,2020,Male
10,45 kg (03.04),Nadezhda Nguen Bulgaria 72 + 83 = 155[n 1]​,Ivana Petrova Bulgaria 67 + 85 = 152[n 1]​,Melisa Güneş Turkey 68 + 83 = 151[n 1]​,2020,Female
3,73 kg (06.04),Daniyar İsmayilov Turkey 160 + 181 = 341,Marin Robu Moldova 156 + 183 = 339,Briken Calja Albania 152 + 184 = 336,2020,Male
7,102 kg (10.04),Samvel Gasparian Armenia 176 +214 = 390,Arsen Martirosian Armenia 171 + 209 = 380,Dadaş Dadaşbəyli Azerbaijan 177 + 202 = 379,2020,Male
11,49 kg (03.04),Monica Csengeri Romania 86 + 103 = 189,Kristina Sobol Russia 85 + 96 = 181,Mihaela Cambei Romania 80 + 100 = 180,2020,Female
18,87 kg (10.04),Daria Ajmerova Russia 108 + 138 = 246,Elena Cîlcic Moldova 107 + 138 = 245,Daria Riazanova Russia 105 + 135 = 240,2020,Female
14,64 kg (06.04),Loredana Toma Romania 114 + 130 = 244,Sarah Davies United Kingdom 101 + 129 = 230,Anastasiya Anzorova Russia 100 + 122 = 222,2020,Female

In [14]:
# Guardar el DataFrame de 2019 traducido
df_2019.to_csv('2019_European_Weightlifting_Championships_data.csv', index=False, encoding='utf-8')

# Guardar el DataFrame de 2020 traducido
df_2020.to_csv('2020_European_Weightlifting_Championships_data.csv', index=False, encoding='utf-8')